### ISSUE TITLE
Negative and Pending numbers missing from some states in states_daily_4pm_et.csv

### ISSUE THREAD

**Issue by johncdavis200** [COVID19Tracking/covid-tracking-data#237]
The latest https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_daily_4pm_et.csv file is missing negative and pending data for the following states:

Alaska, California, Georgia, Kentucky, New York, Ohio, Texas, Virginia and Washington (state).

I have not noticed this problem before today.  The rest of the states appear to be ok - at least they have negative and pending numbers that are non-zero.  

Attached are screen shot examples of the states_daily_4pm_et.csv that I just downloaded:

![KY_no_negatives](https://user-images.githubusercontent.com/62606086/106938106-8f742280-66ec-11eb-86a2-e7a025e514f6.jpg)
![NC_has_negatives](https://user-images.githubusercontent.com/62606086/106938111-91d67c80-66ec-11eb-9b14-2f4b3f03895b.jpg)

**Comment by muamichali** [comment]
Hi @johncdavis200 

We wrote about this in our data faq which you can see here: https://covidtracking.com/about-data/faq#why-are-you-removing-values-from-the-api-field-negative-from-various-states-starting-on-january-27-2021

As part of our larger project of moving to reporting explicit totals for all states, we are also removing negatives that were created from mixed units (specimens minus cases or test encounters minus cases) for states that are using explicit totals in our main total test results field, called totalTestResults in the API. (Check out the above FAQ entry and blog post for more information about changes in our totalTestResults).

Before these states provided full histories of explicit totals, we were using positive plus negative (following early reporting practices of many states) to produce total test counts in order to get a full time-series. When states stopped reporting negatives directly, we computed them by subtracting the cases from the totals, so that positive+negative would equal the new explicitly reported values. In some cases, this led to mixing units in the negative field. Now that these states have provided full histories of their total tests, we have switched them away from positive plus negative for total test results and can remove these mixed unit values.

We are starting with AK, CA, DC, GA, KY, NY, OH, OR, TX, VA and WA on January 27, 2021, and we will continue to remove any negatives mixing units as we switch states over to explicit total test figures.
